/*
* generated by Xtext
*/
package pimar.editor.textual.xwcore;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XwcoreStandaloneSetup extends XwcoreStandaloneSetupGenerated{

	public static void doSetup() {
		new XwcoreStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

