/*
 * generated by Xtext
 */
package pimar.editor.textual.xgcore;

import org.eclipse.xtext.naming.IQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XgcoreRuntimeModule extends pimar.editor.textual.xgcore.AbstractXgcoreRuntimeModule {
	
	/**
	 * This methode is for reference to 
	 * - StylePageSettings
	 * - StyleMenuSettings
	 * because they don't have any name and id to be referenced therefore
	 * a string value is generate for them and it is listed in auto completion
	 * 
	 * @author Parisa Moosavi
	 * @date 20.01.2016
	 */
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return XgcoreQualifiedNameProvider.class;
	}
}
