/*
* generated by Xtext
*/
package pimar.editor.textual.xgcore;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XgcoreStandaloneSetup extends XgcoreStandaloneSetupGenerated{

	public static void doSetup() {
		new XgcoreStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

