/*
 * generated by Xtext
 */
package pimar.editor.textual.xgcore.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XgcoreUiModule extends pimar.editor.textual.xgcore.ui.AbstractXgcoreUiModule {
	public XgcoreUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
