/*
 * generated by Xtext
 */
package pimar.editor.textual.xgcore.ui.contentassist

import pimar.editor.textual.xgcore.ui.contentassist.AbstractXgcoreProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class XgcoreProposalProvider extends AbstractXgcoreProposalProvider {
}
