/*
 * generated by Xtext
 */
package pimar.editor.textual.xgcore.validation

import gcore.RGBColor
import gcore.StyleSetting
import java.util.ArrayList
import gcore.GcorePackage
import org.eclipse.xtext.validation.Check

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class XgcoreValidator extends AbstractXgcoreValidator {
	
	public static val DUPLICATE_COLOR="Gcore_DuplicateColor"

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
	/**
	 * Validation for preventing duplicate colors
	 * @date 07052016
	 */
	@Check
	def CheckNoDuplicateColor(StyleSetting styleSetting){
		var strColor = ""
		val visitedColors = new ArrayList<String>
		for(RGBColor rGBColor : styleSetting.rgbColors){
			strColor = ""
			if(rGBColor.red == 0){
				strColor = strColor + "000"
			}else{
				strColor = strColor + String.format("%03d",rGBColor.red)
			}
			if(rGBColor.green == 0){
				strColor = strColor + "000"
			}else{
				strColor = strColor + String.format("%03d",rGBColor.green)
			}	
			if(rGBColor.blue == 0){
				strColor = strColor + "000"
			}else{
				strColor = strColor + String.format("%03d",rGBColor.blue)
			}	
						
			
			if(visitedColors.contains(strColor)){
				error(
				"The color ["+ rGBColor.name  +"] has been defined before.",
				GcorePackage::eINSTANCE.styleSetting_RgbColors,
				styleSetting.rgbColors.indexOf(rGBColor),
				DUPLICATE_COLOR,
				styleSetting.rgbColors.indexOf(rGBColor).toString)
				
				return
			}else{
				visitedColors.add(strColor)
			}			
		}

	}

}
