/*
 * generated by Xtext
 */
package pimar.editor.textual.xgcore.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import pimar.editor.textual.xgcore.ui.internal.XgcoreActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XgcoreExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XgcoreActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XgcoreActivator.getInstance().getInjector(XgcoreActivator.PIMAR_EDITOR_TEXTUAL_XGCORE_XGCORE);
	}
	
}
