/*
* generated by Xtext
*/
package pimar.editor.textual.xgcore;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XgcoreUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return pimar.editor.textual.xgcore.ui.internal.XgcoreActivator.getInstance().getInjector("pimar.editor.textual.xgcore.Xgcore");
	}
	
}
