/*
* generated by Xtext
*/
package pimar.editor.textual.xwcore.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import pimar.editor.textual.xwcore.services.XwcoreGrammarAccess;

public class XwcoreParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XwcoreGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected pimar.editor.textual.xwcore.parser.antlr.internal.InternalXwcoreParser createParser(XtextTokenStream stream) {
		return new pimar.editor.textual.xwcore.parser.antlr.internal.InternalXwcoreParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ProcessContainer";
	}
	
	public XwcoreGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XwcoreGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
