/*
* generated by Xtext
*/
package pimar.editor.textual.xwcore.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XwcoreAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("pimar/editor/textual/xwcore/parser/antlr/internal/InternalXwcore.tokens");
	}
}
