/*
 * generated by Xtext
 */
package pimar.editor.textual.xwcore.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import pimar.editor.textual.xwcore.ui.internal.XwcoreActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XwcoreExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XwcoreActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XwcoreActivator.getInstance().getInjector(XwcoreActivator.PIMAR_EDITOR_TEXTUAL_XWCORE_XWCORE);
	}
	
}
