/*
 * generated by Xtext
 */
package pimar.editor.textual.xwcore.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XwcoreUiModule extends pimar.editor.textual.xwcore.ui.AbstractXwcoreUiModule {
	public XwcoreUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
