/*
* generated by Xtext
*/
package pimar.editor.textual.xwcore;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XwcoreUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return pimar.editor.textual.xwcore.ui.internal.XwcoreActivator.getInstance().getInjector("pimar.editor.textual.xwcore.Xwcore");
	}
	
}
