/*
 * generated by Xtext
 */
package pimar.editor.textual.xwcore.serializer

import org.eclipse.xtext.Keyword
import org.eclipse.emf.ecore.EObject
import org.eclipse.xtext.nodemodel.ILeafNode
import org.eclipse.xtext.nodemodel.INode

class XwcoreSyntacticSequencer extends AbstractXwcoreSyntacticSequencer {
	
	override protected acceptNode(INode node) {

	}
	
}
