/*
* generated by Xtext
*/
package pimar.editor.textual.xgcore.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import pimar.editor.textual.xgcore.services.XgcoreGrammarAccess;

public class XgcoreParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XgcoreGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected pimar.editor.textual.xgcore.parser.antlr.internal.InternalXgcoreParser createParser(XtextTokenStream stream) {
		return new pimar.editor.textual.xgcore.parser.antlr.internal.InternalXgcoreParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PageContainer";
	}
	
	public XgcoreGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XgcoreGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
