/*
* generated by Xtext
*/
package pimar.editor.textual.xgcore.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import pimar.editor.textual.xgcore.services.XgcoreGrammarAccess;

public class XgcoreParser extends AbstractContentAssistParser {
	
	@Inject
	private XgcoreGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected pimar.editor.textual.xgcore.ui.contentassist.antlr.internal.InternalXgcoreParser createParser() {
		pimar.editor.textual.xgcore.ui.contentassist.antlr.internal.InternalXgcoreParser result = new pimar.editor.textual.xgcore.ui.contentassist.antlr.internal.InternalXgcoreParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPageAccess().getAlternatives(), "rule__Page__Alternatives");
					put(grammarAccess.getMenuablePageAccess().getAlternatives(), "rule__MenuablePage__Alternatives");
					put(grammarAccess.getListablePageAccess().getAlternatives(), "rule__ListablePage__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getListStyleAccess().getAlternatives(), "rule__ListStyle__Alternatives");
					put(grammarAccess.getMenuStyleAccess().getAlternatives(), "rule__MenuStyle__Alternatives");
					put(grammarAccess.getPageContainerAccess().getGroup(), "rule__PageContainer__Group__0");
					put(grammarAccess.getPageContainerAccess().getGroup_1(), "rule__PageContainer__Group_1__0");
					put(grammarAccess.getPageContainerAccess().getGroup_1_1(), "rule__PageContainer__Group_1_1__0");
					put(grammarAccess.getPageContainerAccess().getGroup_5(), "rule__PageContainer__Group_5__0");
					put(grammarAccess.getPageContainerAccess().getGroup_6(), "rule__PageContainer__Group_6__0");
					put(grammarAccess.getPageContainerAccess().getGroup_7(), "rule__PageContainer__Group_7__0");
					put(grammarAccess.getPageContainerAccess().getGroup_7_3(), "rule__PageContainer__Group_7_3__0");
					put(grammarAccess.getPageContainerAccess().getGroup_8(), "rule__PageContainer__Group_8__0");
					put(grammarAccess.getPageContainerAccess().getGroup_8_3(), "rule__PageContainer__Group_8_3__0");
					put(grammarAccess.getPageContainerAccess().getGroup_9(), "rule__PageContainer__Group_9__0");
					put(grammarAccess.getPageContainerAccess().getGroup_9_3(), "rule__PageContainer__Group_9_3__0");
					put(grammarAccess.getPageContainerAccess().getGroup_10(), "rule__PageContainer__Group_10__0");
					put(grammarAccess.getPageContainerAccess().getGroup_10_3(), "rule__PageContainer__Group_10_3__0");
					put(grammarAccess.getPageContainerAccess().getGroup_11(), "rule__PageContainer__Group_11__0");
					put(grammarAccess.getPageContainerAccess().getGroup_11_3(), "rule__PageContainer__Group_11_3__0");
					put(grammarAccess.getPageContainerAccess().getGroup_12(), "rule__PageContainer__Group_12__0");
					put(grammarAccess.getPageContainerAccess().getGroup_12_3(), "rule__PageContainer__Group_12_3__0");
					put(grammarAccess.getMenuAccess().getGroup(), "rule__Menu__Group__0");
					put(grammarAccess.getMenuAccess().getGroup_0(), "rule__Menu__Group_0__0");
					put(grammarAccess.getMenuAccess().getGroup_0_1(), "rule__Menu__Group_0_1__0");
					put(grammarAccess.getStyleSettingAccess().getGroup(), "rule__StyleSetting__Group__0");
					put(grammarAccess.getStyleSettingAccess().getGroup_0(), "rule__StyleSetting__Group_0__0");
					put(grammarAccess.getStyleSettingAccess().getGroup_0_3(), "rule__StyleSetting__Group_0_3__0");
					put(grammarAccess.getStylePageSettingsAccess().getGroup(), "rule__StylePageSettings__Group__0");
					put(grammarAccess.getEditPageAccess().getGroup(), "rule__EditPage__Group__0");
					put(grammarAccess.getEditPageAccess().getGroup_0(), "rule__EditPage__Group_0__0");
					put(grammarAccess.getEditPageAccess().getGroup_0_1(), "rule__EditPage__Group_0_1__0");
					put(grammarAccess.getListPageAccess().getGroup(), "rule__ListPage__Group__0");
					put(grammarAccess.getListPageAccess().getGroup_0(), "rule__ListPage__Group_0__0");
					put(grammarAccess.getListPageAccess().getGroup_0_1(), "rule__ListPage__Group_0_1__0");
					put(grammarAccess.getListPageAccess().getGroup_7(), "rule__ListPage__Group_7__0");
					put(grammarAccess.getViewPageAccess().getGroup(), "rule__ViewPage__Group__0");
					put(grammarAccess.getViewPageAccess().getGroup_0(), "rule__ViewPage__Group_0__0");
					put(grammarAccess.getViewPageAccess().getGroup_0_1(), "rule__ViewPage__Group_0_1__0");
					put(grammarAccess.getViewPageAccess().getGroup_5(), "rule__ViewPage__Group_5__0");
					put(grammarAccess.getCustomPageAccess().getGroup(), "rule__CustomPage__Group__0");
					put(grammarAccess.getCustomPageAccess().getGroup_0(), "rule__CustomPage__Group_0__0");
					put(grammarAccess.getCustomPageAccess().getGroup_0_1(), "rule__CustomPage__Group_0_1__0");
					put(grammarAccess.getLoginPageAccess().getGroup(), "rule__LoginPage__Group__0");
					put(grammarAccess.getLoginPageAccess().getGroup_0(), "rule__LoginPage__Group_0__0");
					put(grammarAccess.getLoginPageAccess().getGroup_0_1(), "rule__LoginPage__Group_0_1__0");
					put(grammarAccess.getProcessSelectorPageAccess().getGroup(), "rule__ProcessSelectorPage__Group__0");
					put(grammarAccess.getProcessSelectorPageAccess().getGroup_0(), "rule__ProcessSelectorPage__Group_0__0");
					put(grammarAccess.getProcessSelectorPageAccess().getGroup_0_1(), "rule__ProcessSelectorPage__Group_0_1__0");
					put(grammarAccess.getProcessSelectorPageAccess().getGroup_5(), "rule__ProcessSelectorPage__Group_5__0");
					put(grammarAccess.getSelectableListPageAccess().getGroup(), "rule__SelectableListPage__Group__0");
					put(grammarAccess.getSelectableListPageAccess().getGroup_0(), "rule__SelectableListPage__Group_0__0");
					put(grammarAccess.getSelectableListPageAccess().getGroup_0_1(), "rule__SelectableListPage__Group_0_1__0");
					put(grammarAccess.getMapPageAccess().getGroup(), "rule__MapPage__Group__0");
					put(grammarAccess.getMapPageAccess().getGroup_0(), "rule__MapPage__Group_0__0");
					put(grammarAccess.getMapPageAccess().getGroup_0_1(), "rule__MapPage__Group_0_1__0");
					put(grammarAccess.getMediaPageAccess().getGroup(), "rule__MediaPage__Group__0");
					put(grammarAccess.getMediaPageAccess().getGroup_0(), "rule__MediaPage__Group_0__0");
					put(grammarAccess.getMediaPageAccess().getGroup_0_1(), "rule__MediaPage__Group_0_1__0");
					put(grammarAccess.getELearningPageAccess().getGroup(), "rule__ELearningPage__Group__0");
					put(grammarAccess.getELearningPageAccess().getGroup_0(), "rule__ELearningPage__Group_0__0");
					put(grammarAccess.getELearningPageAccess().getGroup_0_1(), "rule__ELearningPage__Group_0_1__0");
					put(grammarAccess.getELearningPageAccess().getGroup_5(), "rule__ELearningPage__Group_5__0");
					put(grammarAccess.getTakePicturePageAccess().getGroup(), "rule__TakePicturePage__Group__0");
					put(grammarAccess.getTakePicturePageAccess().getGroup_0(), "rule__TakePicturePage__Group_0__0");
					put(grammarAccess.getTakePicturePageAccess().getGroup_0_1(), "rule__TakePicturePage__Group_0_1__0");
					put(grammarAccess.getRecordAudioPageAccess().getGroup(), "rule__RecordAudioPage__Group__0");
					put(grammarAccess.getRecordAudioPageAccess().getGroup_0(), "rule__RecordAudioPage__Group_0__0");
					put(grammarAccess.getRecordAudioPageAccess().getGroup_0_1(), "rule__RecordAudioPage__Group_0_1__0");
					put(grammarAccess.getARPageAccess().getGroup(), "rule__ARPage__Group__0");
					put(grammarAccess.getARPageAccess().getGroup_0(), "rule__ARPage__Group_0__0");
					put(grammarAccess.getARPageAccess().getGroup_0_1(), "rule__ARPage__Group_0_1__0");
					put(grammarAccess.getRGBColorAccess().getGroup(), "rule__RGBColor__Group__0");
					put(grammarAccess.getRGBColorAccess().getGroup_1(), "rule__RGBColor__Group_1__0");
					put(grammarAccess.getRGBColorAccess().getGroup_1_1(), "rule__RGBColor__Group_1_1__0");
					put(grammarAccess.getRGBColorAccess().getGroup_3(), "rule__RGBColor__Group_3__0");
					put(grammarAccess.getStyleListSettingsAccess().getGroup(), "rule__StyleListSettings__Group__0");
					put(grammarAccess.getStyleListSettingsAccess().getGroup_4(), "rule__StyleListSettings__Group_4__0");
					put(grammarAccess.getStyleSelectionSettingsAccess().getGroup(), "rule__StyleSelectionSettings__Group__0");
					put(grammarAccess.getStyleMenuSettingsAccess().getGroup(), "rule__StyleMenuSettings__Group__0");
					put(grammarAccess.getEStringToStringMapEntryAccess().getGroup(), "rule__EStringToStringMapEntry__Group__0");
					put(grammarAccess.getEAnnotationAccess().getGroup(), "rule__EAnnotation__Group__0");
					put(grammarAccess.getEAnnotationAccess().getGroup_3(), "rule__EAnnotation__Group_3__0");
					put(grammarAccess.getEAnnotationAccess().getGroup_3_2(), "rule__EAnnotation__Group_3_2__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getPageContainerAccess().getEAnnotationsAssignment_1_0(), "rule__PageContainer__EAnnotationsAssignment_1_0");
					put(grammarAccess.getPageContainerAccess().getEAnnotationsAssignment_1_1_1(), "rule__PageContainer__EAnnotationsAssignment_1_1_1");
					put(grammarAccess.getPageContainerAccess().getNameAssignment_3(), "rule__PageContainer__NameAssignment_3");
					put(grammarAccess.getPageContainerAccess().getNsURIAssignment_5_1(), "rule__PageContainer__NsURIAssignment_5_1");
					put(grammarAccess.getPageContainerAccess().getNsPrefixAssignment_6_1(), "rule__PageContainer__NsPrefixAssignment_6_1");
					put(grammarAccess.getPageContainerAccess().getStyleSettingsAssignment_7_2(), "rule__PageContainer__StyleSettingsAssignment_7_2");
					put(grammarAccess.getPageContainerAccess().getStyleSettingsAssignment_7_3_1(), "rule__PageContainer__StyleSettingsAssignment_7_3_1");
					put(grammarAccess.getPageContainerAccess().getMenuesAssignment_8_2(), "rule__PageContainer__MenuesAssignment_8_2");
					put(grammarAccess.getPageContainerAccess().getMenuesAssignment_8_3_1(), "rule__PageContainer__MenuesAssignment_8_3_1");
					put(grammarAccess.getPageContainerAccess().getPagesAssignment_9_2(), "rule__PageContainer__PagesAssignment_9_2");
					put(grammarAccess.getPageContainerAccess().getPagesAssignment_9_3_1(), "rule__PageContainer__PagesAssignment_9_3_1");
					put(grammarAccess.getPageContainerAccess().getMenuablePagesAssignment_10_2(), "rule__PageContainer__MenuablePagesAssignment_10_2");
					put(grammarAccess.getPageContainerAccess().getMenuablePagesAssignment_10_3_1(), "rule__PageContainer__MenuablePagesAssignment_10_3_1");
					put(grammarAccess.getPageContainerAccess().getListablePagesAssignment_11_2(), "rule__PageContainer__ListablePagesAssignment_11_2");
					put(grammarAccess.getPageContainerAccess().getListablePagesAssignment_11_3_1(), "rule__PageContainer__ListablePagesAssignment_11_3_1");
					put(grammarAccess.getPageContainerAccess().getSelectablePagesAssignment_12_2(), "rule__PageContainer__SelectablePagesAssignment_12_2");
					put(grammarAccess.getPageContainerAccess().getSelectablePagesAssignment_12_3_1(), "rule__PageContainer__SelectablePagesAssignment_12_3_1");
					put(grammarAccess.getMenuAccess().getEAnnotationsAssignment_0_0(), "rule__Menu__EAnnotationsAssignment_0_0");
					put(grammarAccess.getMenuAccess().getEAnnotationsAssignment_0_1_1(), "rule__Menu__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getMenuAccess().getNameAssignment_1(), "rule__Menu__NameAssignment_1");
					put(grammarAccess.getMenuAccess().getMenuStyleAssignment_3(), "rule__Menu__MenuStyleAssignment_3");
					put(grammarAccess.getStyleSettingAccess().getRgbColorsAssignment_0_2(), "rule__StyleSetting__RgbColorsAssignment_0_2");
					put(grammarAccess.getStyleSettingAccess().getRgbColorsAssignment_0_3_1(), "rule__StyleSetting__RgbColorsAssignment_0_3_1");
					put(grammarAccess.getStyleSettingAccess().getFontColorAssignment_2(), "rule__StyleSetting__FontColorAssignment_2");
					put(grammarAccess.getStyleSettingAccess().getBackColorAssignment_4(), "rule__StyleSetting__BackColorAssignment_4");
					put(grammarAccess.getStyleSettingAccess().getPageStyleAssignment_5(), "rule__StyleSetting__PageStyleAssignment_5");
					put(grammarAccess.getStyleSettingAccess().getMenuStyleAssignment_6(), "rule__StyleSetting__MenuStyleAssignment_6");
					put(grammarAccess.getStyleSettingAccess().getSelectionStyleAssignment_7(), "rule__StyleSetting__SelectionStyleAssignment_7");
					put(grammarAccess.getStyleSettingAccess().getListStyleAssignment_8(), "rule__StyleSetting__ListStyleAssignment_8");
					put(grammarAccess.getStylePageSettingsAccess().getFrameColorAssignment_2(), "rule__StylePageSettings__FrameColorAssignment_2");
					put(grammarAccess.getStylePageSettingsAccess().getImagePositionAssignment_4(), "rule__StylePageSettings__ImagePositionAssignment_4");
					put(grammarAccess.getStylePageSettingsAccess().getTextPositionAssignment_6(), "rule__StylePageSettings__TextPositionAssignment_6");
					put(grammarAccess.getStylePageSettingsAccess().getFrameAssignment_8(), "rule__StylePageSettings__FrameAssignment_8");
					put(grammarAccess.getEditPageAccess().getEAnnotationsAssignment_0_0(), "rule__EditPage__EAnnotationsAssignment_0_0");
					put(grammarAccess.getEditPageAccess().getEAnnotationsAssignment_0_1_1(), "rule__EditPage__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getEditPageAccess().getNameAssignment_2(), "rule__EditPage__NameAssignment_2");
					put(grammarAccess.getEditPageAccess().getPageStyleAssignment_4(), "rule__EditPage__PageStyleAssignment_4");
					put(grammarAccess.getListPageAccess().getEAnnotationsAssignment_0_0(), "rule__ListPage__EAnnotationsAssignment_0_0");
					put(grammarAccess.getListPageAccess().getEAnnotationsAssignment_0_1_1(), "rule__ListPage__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getListPageAccess().getNameAssignment_2(), "rule__ListPage__NameAssignment_2");
					put(grammarAccess.getListPageAccess().getPageStyleAssignment_4(), "rule__ListPage__PageStyleAssignment_4");
					put(grammarAccess.getListPageAccess().getListablepageStyleAssignment_6(), "rule__ListPage__ListablepageStyleAssignment_6");
					put(grammarAccess.getListPageAccess().getMenuAssignment_7_1(), "rule__ListPage__MenuAssignment_7_1");
					put(grammarAccess.getViewPageAccess().getEAnnotationsAssignment_0_0(), "rule__ViewPage__EAnnotationsAssignment_0_0");
					put(grammarAccess.getViewPageAccess().getEAnnotationsAssignment_0_1_1(), "rule__ViewPage__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getViewPageAccess().getNameAssignment_2(), "rule__ViewPage__NameAssignment_2");
					put(grammarAccess.getViewPageAccess().getPageStyleAssignment_4(), "rule__ViewPage__PageStyleAssignment_4");
					put(grammarAccess.getViewPageAccess().getMenuAssignment_5_1(), "rule__ViewPage__MenuAssignment_5_1");
					put(grammarAccess.getCustomPageAccess().getEAnnotationsAssignment_0_0(), "rule__CustomPage__EAnnotationsAssignment_0_0");
					put(grammarAccess.getCustomPageAccess().getEAnnotationsAssignment_0_1_1(), "rule__CustomPage__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getCustomPageAccess().getNameAssignment_2(), "rule__CustomPage__NameAssignment_2");
					put(grammarAccess.getCustomPageAccess().getPageStyleAssignment_4(), "rule__CustomPage__PageStyleAssignment_4");
					put(grammarAccess.getLoginPageAccess().getEAnnotationsAssignment_0_0(), "rule__LoginPage__EAnnotationsAssignment_0_0");
					put(grammarAccess.getLoginPageAccess().getEAnnotationsAssignment_0_1_1(), "rule__LoginPage__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getLoginPageAccess().getNameAssignment_2(), "rule__LoginPage__NameAssignment_2");
					put(grammarAccess.getLoginPageAccess().getPageStyleAssignment_4(), "rule__LoginPage__PageStyleAssignment_4");
					put(grammarAccess.getProcessSelectorPageAccess().getEAnnotationsAssignment_0_0(), "rule__ProcessSelectorPage__EAnnotationsAssignment_0_0");
					put(grammarAccess.getProcessSelectorPageAccess().getEAnnotationsAssignment_0_1_1(), "rule__ProcessSelectorPage__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getProcessSelectorPageAccess().getNameAssignment_2(), "rule__ProcessSelectorPage__NameAssignment_2");
					put(grammarAccess.getProcessSelectorPageAccess().getPageStyleAssignment_4(), "rule__ProcessSelectorPage__PageStyleAssignment_4");
					put(grammarAccess.getProcessSelectorPageAccess().getMenuAssignment_5_1(), "rule__ProcessSelectorPage__MenuAssignment_5_1");
					put(grammarAccess.getSelectableListPageAccess().getEAnnotationsAssignment_0_0(), "rule__SelectableListPage__EAnnotationsAssignment_0_0");
					put(grammarAccess.getSelectableListPageAccess().getEAnnotationsAssignment_0_1_1(), "rule__SelectableListPage__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getSelectableListPageAccess().getMultiSelectionAssignment_1(), "rule__SelectableListPage__MultiSelectionAssignment_1");
					put(grammarAccess.getSelectableListPageAccess().getNameAssignment_3(), "rule__SelectableListPage__NameAssignment_3");
					put(grammarAccess.getSelectableListPageAccess().getPageStyleAssignment_5(), "rule__SelectableListPage__PageStyleAssignment_5");
					put(grammarAccess.getSelectableListPageAccess().getSelectablepageStyleAssignment_7(), "rule__SelectableListPage__SelectablepageStyleAssignment_7");
					put(grammarAccess.getSelectableListPageAccess().getListablepageStyleAssignment_9(), "rule__SelectableListPage__ListablepageStyleAssignment_9");
					put(grammarAccess.getMapPageAccess().getEAnnotationsAssignment_0_0(), "rule__MapPage__EAnnotationsAssignment_0_0");
					put(grammarAccess.getMapPageAccess().getEAnnotationsAssignment_0_1_1(), "rule__MapPage__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getMapPageAccess().getNameAssignment_2(), "rule__MapPage__NameAssignment_2");
					put(grammarAccess.getMapPageAccess().getPageStyleAssignment_4(), "rule__MapPage__PageStyleAssignment_4");
					put(grammarAccess.getMediaPageAccess().getEAnnotationsAssignment_0_0(), "rule__MediaPage__EAnnotationsAssignment_0_0");
					put(grammarAccess.getMediaPageAccess().getEAnnotationsAssignment_0_1_1(), "rule__MediaPage__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getMediaPageAccess().getNameAssignment_2(), "rule__MediaPage__NameAssignment_2");
					put(grammarAccess.getMediaPageAccess().getPageStyleAssignment_4(), "rule__MediaPage__PageStyleAssignment_4");
					put(grammarAccess.getELearningPageAccess().getEAnnotationsAssignment_0_0(), "rule__ELearningPage__EAnnotationsAssignment_0_0");
					put(grammarAccess.getELearningPageAccess().getEAnnotationsAssignment_0_1_1(), "rule__ELearningPage__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getELearningPageAccess().getNameAssignment_2(), "rule__ELearningPage__NameAssignment_2");
					put(grammarAccess.getELearningPageAccess().getPageStyleAssignment_4(), "rule__ELearningPage__PageStyleAssignment_4");
					put(grammarAccess.getELearningPageAccess().getMenuAssignment_5_1(), "rule__ELearningPage__MenuAssignment_5_1");
					put(grammarAccess.getTakePicturePageAccess().getEAnnotationsAssignment_0_0(), "rule__TakePicturePage__EAnnotationsAssignment_0_0");
					put(grammarAccess.getTakePicturePageAccess().getEAnnotationsAssignment_0_1_1(), "rule__TakePicturePage__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getTakePicturePageAccess().getNameAssignment_2(), "rule__TakePicturePage__NameAssignment_2");
					put(grammarAccess.getTakePicturePageAccess().getPageStyleAssignment_4(), "rule__TakePicturePage__PageStyleAssignment_4");
					put(grammarAccess.getRecordAudioPageAccess().getEAnnotationsAssignment_0_0(), "rule__RecordAudioPage__EAnnotationsAssignment_0_0");
					put(grammarAccess.getRecordAudioPageAccess().getEAnnotationsAssignment_0_1_1(), "rule__RecordAudioPage__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getRecordAudioPageAccess().getNameAssignment_2(), "rule__RecordAudioPage__NameAssignment_2");
					put(grammarAccess.getRecordAudioPageAccess().getPageStyleAssignment_4(), "rule__RecordAudioPage__PageStyleAssignment_4");
					put(grammarAccess.getARPageAccess().getEAnnotationsAssignment_0_0(), "rule__ARPage__EAnnotationsAssignment_0_0");
					put(grammarAccess.getARPageAccess().getEAnnotationsAssignment_0_1_1(), "rule__ARPage__EAnnotationsAssignment_0_1_1");
					put(grammarAccess.getARPageAccess().getNameAssignment_2(), "rule__ARPage__NameAssignment_2");
					put(grammarAccess.getARPageAccess().getPageStyleAssignment_4(), "rule__ARPage__PageStyleAssignment_4");
					put(grammarAccess.getRGBColorAccess().getEAnnotationsAssignment_1_0(), "rule__RGBColor__EAnnotationsAssignment_1_0");
					put(grammarAccess.getRGBColorAccess().getEAnnotationsAssignment_1_1_1(), "rule__RGBColor__EAnnotationsAssignment_1_1_1");
					put(grammarAccess.getRGBColorAccess().getNameAssignment_2(), "rule__RGBColor__NameAssignment_2");
					put(grammarAccess.getRGBColorAccess().getRedAssignment_3_1(), "rule__RGBColor__RedAssignment_3_1");
					put(grammarAccess.getRGBColorAccess().getGreenAssignment_3_3(), "rule__RGBColor__GreenAssignment_3_3");
					put(grammarAccess.getRGBColorAccess().getBlueAssignment_3_5(), "rule__RGBColor__BlueAssignment_3_5");
					put(grammarAccess.getStyleListSettingsAccess().getSeparatorShowAssignment_0(), "rule__StyleListSettings__SeparatorShowAssignment_0");
					put(grammarAccess.getStyleListSettingsAccess().getSeparatorColorAssignment_3(), "rule__StyleListSettings__SeparatorColorAssignment_3");
					put(grammarAccess.getStyleListSettingsAccess().getListStyleAssignment_4_1(), "rule__StyleListSettings__ListStyleAssignment_4_1");
					put(grammarAccess.getStyleSelectionSettingsAccess().getSelectionColorAssignment_2(), "rule__StyleSelectionSettings__SelectionColorAssignment_2");
					put(grammarAccess.getStyleMenuSettingsAccess().getFixedMenuAssignment_1(), "rule__StyleMenuSettings__FixedMenuAssignment_1");
					put(grammarAccess.getStyleMenuSettingsAccess().getMenuStyleAssignment_4(), "rule__StyleMenuSettings__MenuStyleAssignment_4");
					put(grammarAccess.getEStringToStringMapEntryAccess().getKeyAssignment_1(), "rule__EStringToStringMapEntry__KeyAssignment_1");
					put(grammarAccess.getEStringToStringMapEntryAccess().getValueAssignment_3(), "rule__EStringToStringMapEntry__ValueAssignment_3");
					put(grammarAccess.getEAnnotationAccess().getSourceAssignment_2(), "rule__EAnnotation__SourceAssignment_2");
					put(grammarAccess.getEAnnotationAccess().getDetailsAssignment_3_1(), "rule__EAnnotation__DetailsAssignment_3_1");
					put(grammarAccess.getEAnnotationAccess().getDetailsAssignment_3_2_1(), "rule__EAnnotation__DetailsAssignment_3_2_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			pimar.editor.textual.xgcore.ui.contentassist.antlr.internal.InternalXgcoreParser typedParser = (pimar.editor.textual.xgcore.ui.contentassist.antlr.internal.InternalXgcoreParser) parser;
			typedParser.entryRulePageContainer();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public XgcoreGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XgcoreGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
